version: "3.7"

services:

  nginx:
    image: ujhgj/newsletter-demo-nginx:0.0.1

  php-fpm:
    image: ujhgj/newsletter-demo-php:0.0.1
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  sender:
    image: ujhgj/newsletter-demo-php:0.0.1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  cron:
    image: ujhgj/newsletter-demo-php:0.0.1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
